version: '3'
services:
  es1:
    container_name: es1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
#      - node.name=es1
#      - cluster.name=nori-cluster
#      - cluster.initial_master_nodes=es1,es2
#      - discovery.seed_hosts=es2
#      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS= -Xms1g -Xmx1g
#      - xpack.security.enabled=false
    volumes:
      - esvol1:/usr/share/elasticsearch/data
      - ./elasticsearch-es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
#      - 9301:9300
  es2:
    container_name: es2
    depends_on:
      - es1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
#      - node.name=es2
#      - cluster.name=nori-cluster
#      - cluster.initial_master_nodes=es1,es2
#      - discovery.seed_hosts=es2
#      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS= -Xms1g -Xmx1g
#      - xpack.security.enabled=false
    volumes:
      - esvol2:/usr/share/elasticsearch/data
      - ./elasticsearch-es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    ports:
#      - 9202:9200
#      - 9302:9300
  kibana:
    container_name: kibana
    depends_on:
      - es1
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
    - 5601:5601
volumes:
  esvol1:
  esvol2:
#networks:
#  default:
#    driver: host

#todo volume v, network v, kibana v